### ISSUE TITLE
Inventory Setups bugging out all the time

### ISSUE THREAD

**Issue by thhdragon** [Owain94/OpenOSRS-RL-hub#165]
my inventory setup keeps going buggy lately, not filtering my bank and plugin not recognizing im wearing the gear or have an item in the right space (shows the red highlighted square like its wrong). im constantly having to uninstall and reinstall it to get it temporarily working again, i can get a log if it will help

**Comment by emiljensen2** [comment]
Yeah same

**Comment by emiljensen2** [comment]
2020-09-20 11:45:04 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.reflect.InvocationTargetException
	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:83)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at com.jakewharton.rxrelay3.PublishRelay$PublishDisposable.onNext(PublishRelay.java:179)
	at com.jakewharton.rxrelay3.PublishRelay.accept(PublishRelay.java:144)
	at com.jakewharton.rxrelay3.SerializedRelay.accept(SerializedRelay.java:57)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:115)
	at net.runelite.client.callback.Hooks.post(Hooks.java:175)
	at bm.ha(SecureRandomCallable.java:1411)
	at hq.hv(Widget.java:7246)
	at client.copy$menu(Client.java:7169)
	at client.hk(Client.java:1722)
	at client.fs(Client.java:3052)
	at client.at(Client.java:1190)
	at bw.r(GameShell.java:334)
	at bw.run(GameShell.java:313)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor254.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.runelite.client.plugins.Plugin.lambda$findSubscriptions$1(Plugin.java:104)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 17 common frames omitted
Caused by: java.lang.NullPointerException: null
	at net.runelite.client.plugins.inventorysetups.InventorySetupPlugin.onMenuOptionClicked(InventorySetupPlugin.java:485)
	... 22 common frames omitted

**Comment by Im2be** [comment]
This happened consistently a few months ago when leaving a raid. Has been fixed for a while now.
